
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghucegvhempgmdykosiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdodWNlZ3ZoZW1wZ21keWtvc2l3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxODQ2NTYsImV4cCI6MjA1OTc2MDY1Nn0.oQ3cMuXpgo0N29zgvZq2kr3a59Gv0fX7qj6U97vIMck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storageKey: 'happy-sprout-auth',
      flowType: 'pkce', // Enable modern PKCE flow for more secure auth
    },
    db: {
      schema: 'public'
    },
    global: {
      headers: {
        'Content-Type': 'application/json'
      }
    }
  }
);
